### ISSUE TITLE
Adding TOML comments in the remappings (foundry.toml) breaks resolution

### ISSUE THREAD

**Issue by beeb** [defi-wonderland/natspec-smells#64]
The resolution of remappings from the foundry.toml file are broken when the file contains comments within the remappings table. This is because natspec-smells uses custom string parsing instead of a proper TOML parser.

Repro:

```toml
remappings = [
    "forge-std=dependencies/forge-std-1.9.2/src/", # this is a comment
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/"
]
```
